#!/bin/bash

# Stop MySQL service
sudo systemctl stop mysql

# Restart MySQL service
sudo systemctl restart mysql

# Purge MySQL (remove all data and configurations)
sudo apt-get purge mysql-server mysql-client mysql-common mysql-server-core-* mysql-client-core-*

# Remove any remaining MySQL files and directories
sudo rm -rf /etc/mysql /var/lib/mysql

